// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteUser.sql

package database

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
TRUNCATE users
`

func (q *Queries) DeleteUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUser)
	return err
}
