// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getFeedFollowsForUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedsFollowForUser = `-- name: GetFeedsFollowForUser :many
SELECT ff.id, f.name as feedName, u.name as userName
FROM feed_follows ff
INNER JOIN feeds f ON ff.feed_id = f.id
INNER JOIN users u ON ff.user_id = u.id
WHERE ff.user_id = $1
`

type GetFeedsFollowForUserRow struct {
	ID       uuid.UUID
	Feedname string
	Username string
}

func (q *Queries) GetFeedsFollowForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedsFollowForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsFollowForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsFollowForUserRow
	for rows.Next() {
		var i GetFeedsFollowForUserRow
		if err := rows.Scan(&i.ID, &i.Feedname, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
