// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getNextFeedToFecth.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT f.id, f.name as feedName, f.url as feedUrl
FROM feed_follows ff
INNER JOIN feeds f ON ff.feed_id = f.id
INNER JOIN users u ON ff.user_id = u.id
WHERE u.ID = $1
ORDER BY f.last_fetched_at ASC NULLS FIRST
LIMIT 1
`

type GetNextFeedToFetchRow struct {
	ID       uuid.UUID
	Feedname string
	Feedurl  string
}

func (q *Queries) GetNextFeedToFetch(ctx context.Context, id uuid.UUID) (GetNextFeedToFetchRow, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch, id)
	var i GetNextFeedToFetchRow
	err := row.Scan(&i.ID, &i.Feedname, &i.Feedurl)
	return i, err
}
